A/A/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
                  # Django Admin
                  path('admin/', admin.site.urls),
                  # User Management
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  # Local App
                  path('', include('pages.urls', namespace='pages')),
                  path('orders/', include('orders.urls', namespace='orders')),
                  path('products/', include('products.urls', namespace='products')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

A/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('order/', views.OrderView.as_view(), name='order_item'),
    path('create/order/', views.create_order, name='create_order'),
    path('cart/', views.OrderSummaryView.as_view(), name='summary_cart'),
    # this under usl`s for add and remove and delete product from order
    path('add/<slug:product_slug>/', views.add_to_cart, name='add_cart'),
    path('remove/cart/<slug:product_slug>/', views.remove_from_cart, name='remove_cart'),
    path('remove/one/<slug:product_slug>/', views.remove_one_cart, name='remove_one_cart'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),

]

A/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('brand/<slug:brand_slug>/', views.HomeView.as_view(), name='brand_slug'),
    path('category/<slug:slug_category>', views.HomeView.as_view(), name='category_slug'),
    # show product in pages
    path('<slug:slug>/', views.ProductsDetailView.as_view(), name='product_detail'),

    # Commend
    path('reply/<int:product_id>/<int:commend_id>/', views.AddCommendView.as_view(), name='add_reply'),
]

A/pages/templates/pages/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <!--one-slider-->
            <div>
                <div>
                    <div class="center-block ">
                        <div class="slider ">

                            <img src="{{ product.image.url }}" height="250px">
                            <h4>{{ product.title }}</h4>
                            <p>{{ product.price }}</p>
                            <p>{{ product.description_long|safe }}</p>
                            <hr>
                            <a href="{% url 'orders:add_cart' product.slug %}" methods="post" class="btn btn-outline-info"> Add to Cart</a>

                        </div>

                    </div>


                    <div>
                        <br>
                        <br>
                        <br>
                        <p>نظرات:</p>
                        <br>
                        <br>
                        <br>
                        {% for commend in commends %}
                        <p>{{ commend.body|safe }}</p>

                    </div>

                    <div>
                        {% if request.user.is_authenticated %}
                        <form action="{% url 'pages:add_reply' product.id commend.id %}" method="post">
                            {{ form_reply.as_p }}
                            {% csrf_token %}
                            <input type="submit" value="Send">
                        </form>
                        {% endif %}
                    </div>

                    <div>
                        {% with replies=commend.reply_commend.all %}
                        {% for reply in replies %}
                        <p> {{reply.body}} </p>
                        {% endfor %}
                        {% endwith %}
                        {% endfor %}
                        <form action="" method="post">
                            {{ form.as_p }}
                            {% csrf_token %}
                            <input type="submit" value="Send">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <br>
</div>
<div>

</div>


{% endblock %}

A/pages/templates/pages/home.html
{% extends 'blankpage.html' %}
{% block head %}
{% endblock %}


{% block content %}
<div class="main-menu">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul>
                    <li>
                        <a href="#">کالای دیجیتال</a>
                        <ul>
                            <li><a href="#">گوشی موبایل</a></li>
                            <li><a href="#">تبلت</a></li>
                            <li><a href="#">لپ تاپ</a></li>
                            <li><a href="#">نمایشگر</a></li>
                            <li><a href="#">دوربین عکاسی</a></li>
                            <li><a href="#">لوازم جانبی رایانه</a></li>
                            <li><a href="#">لوازم جانبی موبایل</a></li>
                            <li><a href="#">سایر</a></li>
                        </ul>
                    </li>
                    <li><a href="#">آرایشی و بهداشتی</a></li>
                    <li>
                        <a href="#">مد و پوشاک</a>
                        <ul>
                            <li><a href="#">لباس فصل</a></li>
                            <li><a href="#">ساعت مچی</a></li>
                            <li><a href="#">بدلیجات</a></li>
                        </ul>
                    </li>
                    <li><a href="#">خانه و آشپزخانه</a></li>
                    <li><a href="#">ابزار اداری</a></li>
                    <li><a href="#">اسباب بازی</a></li>
                    <li>
                        <a href="#">اخبار</a>
                        <ul>
                            <li><a href="#">تکنولوژی</a></li>
                            <li><a href="#">علم و دانش</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<br>
{% endblock %}

A/pages/templates/pages/index.html
{% extends 'base.html' %}
{% load humanize %}
{% block head %}


{% endblock head %}
{% block category %}

{% for item in categories %}


<div class="btn-group" role="group">

    <button id="btnGroupDrop1" type="button" class="btn btn-outline-light dropdown-toggle" data-bs-toggle="dropdown"
            aria-expanded="false">
        {{ item.name }}
    </button>


    <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
        {% for sub in item.scategory.all %}
        <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>
        {% endfor %}
    </div>

{% endfor %}


{% endblock category %}

{% block content %}
{% for item in brand %}
<a href="{% url 'pages:brand_slug' item.slug %}" class="btn btn-outline-dark">{{ item.name }}</a>
{% endfor %}
<hr>
<!---------------product------------------->
<div class="container">
    <div class="row">
        {% for item in products %}
        <div class="col col-2">
            <div class="card" style="width:100% ;">
                <img class="card-img-top " src="{{ item.image.url }}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{ item.title }}</h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ item.price|intcomma:False }} تومان <i class="icofont-price"></i></li>
                </ul>
                <div class="btn-group btn-sm">
                    <!--button add to cart -->
                    <a href="{% url 'orders:add_cart' item.slug %}" type="button"
                       class="btn btn-col-6 btn-sm btn-outline-danger">افزودن</a>
                    <!-- button info product -->
                    <a href="{{ item.get_absolute_url }}" type="button" class="btn btn-col-4 btn-outline-info btn-sm">اطلاعات</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


<form action="" novalidate>
    {% csrf_token %}
    min:{{ filter.filter_min }}
    <hr>
    max:{{ filter.filter_max }}
    <br>
    <input type="submit" value="فیلتر" class="btn btn-outline-info">
</form>





{% endblock %}