A/A/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
                  # Django Admin
                  path('admin/', admin.site.urls),
                  # User Management
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  # Local App
                  path('', include('pages.urls', namespace='pages')),
                  path('orders/', include('orders.urls', namespace='orders')),
                  path('products/', include('products.urls', namespace='products')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

A/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('order/', views.OrderView.as_view(), name='order_item'),
    path('create/order/', views.create_order, name='create_order'),
    path('cart/', views.OrderSummaryView.as_view(), name='summary_cart'),
    # this under usl`s for add and remove and delete product from order
    path('add/<slug:product_slug>/', views.add_to_cart, name='add_cart'),
    path('remove/cart/<slug:product_slug>/', views.remove_from_cart, name='remove_cart'),
    path('remove/one/<slug:product_slug>/', views.remove_one_cart, name='remove_one_cart'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),

]

A/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('brand/<slug:brand_slug>/', views.HomeView.as_view(), name='brand_slug'),
    path('category/<slug:slug_category>', views.HomeView.as_view(), name='category_slug'),
    # show product in pages
    path('<slug:slug>/', views.ProductsDetailView.as_view(), name='product_detail'),

    # Commend
    path('reply/<int:product_id>/<int:commend_id>/', views.AddCommendView.as_view(), name='add_reply'),
]

A/orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from products.models import Products

User = get_user_model()


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر', related_name='cart_user')
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Products, on_delete=models.CASCADE, related_name='order_product')
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.quantity}تا{self.item.title}"

    def price_item(self):
        price = self.item.price * self.quantity
        return price

    class Meta:
        verbose_name_plural = "سبد خرید"


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='نام کاربر')
    items = models.ManyToManyField(Cart, verbose_name='محصولات')
    start_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')
    ordered_date = models.DateTimeField(verbose_name='تاریخ سفارش', null=True, blank=True)
    address = models.CharField(max_length=500, blank=True, null=True, verbose_name='آدرس')
    ordered = models.BooleanField(default=False, verbose_name='سفارش داده شده است')
    all_price = models.IntegerField(verbose_name='کل ارزش خرید بدون تخفیف', null=True, blank=True)
    price_pey = models.IntegerField(verbose_name='کل مبلغ پرداخت شده', null=True, blank=True)
    price_coupon = models.IntegerField(verbose_name='مبلغ کد تخفیف', null=True, blank=True)

    # --------------
    __original_price = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_price = self.all_price

    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        if self.all_price != self.__original_price:
            self.price_pey = None
            self.price_coupon = None
        super().save(force_insert, force_update, *args, **kwargs)

        self.__original_price = self.all_price

    def total(self):
        item = self.items.all()
        var = 0
        for i in item:
            var += i.item.price * i.quantity
        return var

    def pay(self):
        if self.price_coupon:
            return self.all_price - self.price_coupon
        else:
            return self.all_price

    def __str__(self):
        return f"{self.user.phone_number}"


    class Meta:
        verbose_name_plural = "سفارش"


class Coupon(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='related_in_coupon')
    code = models.CharField(max_length=15, null=True, blank=True, help_text="Auto Dont Need To Add")
    amount = models.IntegerField(verbose_name='مقدار', null=True, blank=True)
    min_order = models.IntegerField(verbose_name='حداقل سفارش ', null=True, blank=True)
    is_active = models.BooleanField(default=False, verbose_name='فعال')
    create = models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ')
    expiry = models.jDateTimeField(auto_now=True, verbose_name='تاریخ انتضا')

    def __str__(self):
        return str(self.code)

    class Meta:
        verbose_name = 'کد تخفیف'
        verbose_name_plural = 'کد تخفیف ها '

A/orders/forms.py
from django import forms


class ApplyCouponForm(forms.Form):
    coupon = forms.CharField(label="کد تخفیف", required=False,
                             widget=forms.TextInput(attrs={'class': 'class-alert alert col-md-2'}))

A/orders/views.py
import json

import requests
from A.settings import MERCHANT, description, ZP_API_VERIFY, ZP_API_STARTPAY, ZP_API_REQUEST, CallbackURL
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from permissions import AddressIsNotNone, CartIsNotNone

from .forms import ApplyCouponForm
from .models import Coupon, Order, Cart
from .services import calculate_discounted_price, get_order_by_id, update_items_quantity, complete_order, \
    calculate_total_price

User = get_user_model()




class OrderSummaryView(LoginRequiredMixin, View):
    """ for show information cart
    if user input a code coupon in form
    validate  and true apply
    """

    templates_class = 'orders/summary.html'

    def get(self, request):
        cart = Cart.objects.filter(user=request.user, ordered=False)
        if cart:
            total_price = calculate_total_price(cart)
            return render(request, self.templates_class, {'cart': cart, 'total_price': total_price})
        return render(request, self.templates_class)


class OrderView(LoginRequiredMixin, AddressIsNotNone, CartIsNotNone, View):
    template_name = 'orders/receipt_coupon.html'
    form_class = ApplyCouponForm

    def setup(self, request, *args, **kwargs):
        self.order = Order.objects.get(user=request.user)
        return super().setup(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form, 'order': self.order})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            coupon = form.cleaned_data['coupon']
            try:
                amount = request.user.related_in_coupon.get(code=coupon, is_active=True)
            except Coupon.DoesNotExist:
                messages.error(request, 'کد تخفیف معتبر نیست', 'danger')
                return redirect('orders:order_item')

            if self.order.all_price < amount.min_order:
                messages.info(request, f'حداقل مقدار خرید برای کد تخفیف {amount.min_order} میباشد', 'info')
                return redirect('orders:order_item')

            discounted_price = calculate_discounted_price(self.order.all_price, amount.amount)
            self.order.price_pey = discounted_price
            self.order.price_coupon = amount.amount
            self.order.save()

            messages.success(request,
                             f'کد تخفیف با موفقیت اعمال شد. مبلغ {amount.amount} کاهش یافت و مبلغ قابل پرداخت {discounted_price} می باشد',
                             'success')
            return redirect('orders:order_item')

        messages.error(request, 'فرم نامعتبر است', 'danger')
        return redirect('orders:order_item')


class OrderPayView(LoginRequiredMixin, View):
    def get(self, request, order_id):
        order = get_order_by_id(order_id)
        request.session['order_pay'] = {'order_id': order.id}
        amount = order.pay()
        data = {
            "merchant_id": MERCHANT,
            "amount": amount,
            "callback_url": CallbackURL,
            "description": description,
            "metadata": {"mobile": request.user, "email": request.user.profile.email}
        }
        headers = {"accept": "application/json", "content-type": "application/json"}
        response = requests.post(url=ZP_API_REQUEST, data=json.dumps(data), headers=headers)
        response_json = response.json()
        if len(response_json.get('errors', [])) == 0:
            authority = response_json['data']['authority']
            return redirect(ZP_API_STARTPAY.format(authority=authority))
        else:
            error = response_json['errors']
            return HttpResponse(f"Error code: {error['code']}, Error Message: {error['message']}")


class OrderVerifyView(LoginRequiredMixin, View):
    def get(self, request):
        order_id = request.session['order_pay']['order_id']
        order = get_order_by_id(order_id)
        update_items_quantity(order)
        complete_order(order)

        status = request.GET.get('Status')
        authority = request.GET['Authority']
        if status == 'OK':
            data = {
                "merchant_id": MERCHANT,
                "amount": order.total(),
                "authority": authority
            }
            headers = {"accept": "application/json", "content-type": "application/json"}
            response = requests.post(url=ZP_API_VERIFY, data=json.dumps(data), headers=headers)
            response_json = response.json()
            if len(response_json.get('errors', [])) == 0:
                t_status = response_json['data']['code']
                if t_status == 100:
                    return HttpResponse('Transaction success.\nRefID: ' + str(response_json['data']['ref_id']))
                elif t_status == 101:
                    return HttpResponse('Transaction submitted : ' + str(response_json['data']['message']))
                else:
                    return HttpResponse('Transaction failed.\nStatus: ' + str(response_json['data']['message']))
            else:
                error = response_json['errors']
                return HttpResponse(f"Error code: {error['code']}, Error Message: {error['message']}")
        else:
            return HttpResponse('Transaction failed or canceled by user')

A/orders/templates/orders/receipt_coupon.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block head %}
<style> .text{color:red;} </style>
{% endblock head %}

{% block content %}
<table class="table col">
    <tbody>
    <tr>
        <th scope="col">نام خریدار</th>
        <td>{{ order.user.profile.first_name }}</td>
    </tr>
    <tr>
        <th scope="col">فامیلی خریدار</th>
        <td>{{ order.user.profile.last_name }}</td>
    </tr>
    <tr>
        <th scope="col">شماره تلفن</th>
        <td>{{ order.user }}</td>
    </tr>
    <tr>
        <th scope="col">آدرس</th>
        <td>{{ order.address }}</td>
    </tr>
    <tr>
        <th>......</th>
        <th scope="col">نام محصول</th>
        <th scope="col">قیمت هر واحد</th>
        <th scope="col">تعداد</th>
        <th scope="col">قیمت کل</th>
    </tr>
    {% for item in order.items.all %}
    <tr>

        <th scope="col">{{ forloop.counter }}</th>

        <td>{{ item.item.title }}</td>
        <td>{{ item.item.price|intcomma:False }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.price_item|intcomma:False }}</td>

    </tr>
    {% endfor %}

    <tr>

        <th scope="col">مبلغ قابل پرداخت</th>
        <th colspan="3"></th>

        <th >{{ order.all_price|intcomma:False }}</th>
    </tr>

{% if order.price_pey %}
    <tr>
        <td class="text"><strong>کد تخفیف شما اعمال شد</strong></td>
        <td colspan="2"></td>
        <td class="text">مبلغ قابل پرداخت جدید</td>
        <td class="text"><strong> {{ order.price_pey|intcomma:False }}</strong></td>
    </tr>
{% endif %}
    </tbody>

</table>

<form action="" method="post" novalidate>
    {{ form.as_p }}
    {% csrf_token %}

    <input type="submit" value="اعمال" class="btn btn-outline-primary">
</form>
 <a class="btn btn-outline-danger" href="{% url 'orders:order_pay' order.id %}" >  پرداخت</a>
{% endblock content %}

A/orders/templates/orders/summary.html
{% extends 'base.html' %}

{% load humanize %}
{% block head  %}
<style>
    .none_line{text-decoration: none;}




</style>
{% endblock head %}
{% block content %}

{% if cart  %}
<table class="table">
    <thead>
    <tr>
        <th scope="col">ردیف</th>
        <th scope="col">نام محصول</th>
        <th scope="col">قیمت</th>
        <th scope="col">تعداد</th>
        <th scope="col">قیمت کل</th>
        <th scope="col">وضعیت</th>
    </tr>

    {% for object in cart %}


    <tbody>
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ object.item.title }}</td>
        <td>{{ object.item.price|intcomma:False }}</td>
        <td>{{ object.quantity|intcomma:False }}</td>
        <td>{{ object.price_item|intcomma:False }}</td>
        <td>
            <a href="{% url 'orders:remove_cart' object.item.slug %}" class="btn btn-danger"><i
                    class="icofont-trash"></i></a>
            <a href="{% url 'orders:remove_one_cart' object.item.slug %}" class="btn btn-warning"><i
                    class="icofont-ui-remove"></i></a>
            <a href="{% url 'orders:add_cart' object.item.slug %}" class="btn btn-primary"><i
                    class="icofont-ui-add"></i></a>
        </td>
    </tr>
    </tbody>
    {% endfor %}
    <tr>
        <td>{{ price_item }}</td>
        <td>قیمت کل</td>
        <td colspan="2"></td>
        <td>
            {{ total_price|intcomma:False }}
        </td>
    </tr>
</table>


<a class="btn btn-outline-info" href="{% url 'orders:create_order' %}">NEXT</a>


{% else %}
<p class=" text-center ">سبد خرید شما خالی است برای خرید به <a class="none_line" href="{% url 'pages:home' %}">اینجا</a>
    بروید </p>

{% endif %}

{% endblock %}