A/A/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
                  # Django Admin
                  path('admin/', admin.site.urls),
                  # User Management
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  # Local App
                  path('', include('pages.urls', namespace='pages')),
                  path('orders/', include('orders.urls', namespace='orders')),
                  path('products/', include('products.urls', namespace='products')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

A/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('verify/', views.VerifyCodeRegisterView.as_view(), name='verify_code'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    # profile user
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('change/profile/', views.ChangeProfile.as_view(), name='change_profile'),
    path('change/date-of-birth/', views.ChangeDateBirth.as_view(), name='change_birth'),
    path('change/password/', views.ChangePasswordView.as_view(), name='change_password'),
    # this part for forget password
    path('forget/password/', views.ForgetPasswordView.as_view(), name='forget_password'),
    path('verify/password/', views.VerifyCodePasswordView.as_view(), name='verify_password'),
    path('create/password/', views.CreateNewPasswordView.as_view(), name='create_password'),

]

A/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('order/', views.OrderView.as_view(), name='order_item'),
    path('create/order/', views.create_order, name='create_order'),
    path('cart/', views.OrderSummaryView.as_view(), name='summary_cart'),
    # this under usl`s for add and remove and delete product from order
    path('add/<slug:product_slug>/', views.add_to_cart, name='add_cart'),
    path('remove/cart/<slug:product_slug>/', views.remove_from_cart, name='remove_cart'),
    path('remove/one/<slug:product_slug>/', views.remove_one_cart, name='remove_one_cart'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),

]

A/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('brand/<slug:brand_slug>/', views.HomeView.as_view(), name='brand_slug'),
    path('category/<slug:slug_category>', views.HomeView.as_view(), name='category_slug'),
    # show product in pages
    path('<slug:slug>/', views.ProductsDetailView.as_view(), name='product_detail'),

    # Commend
    path('reply/<int:product_id>/<int:commend_id>/', views.AddCommendView.as_view(), name='add_reply'),
]

A/templates/base.html
<!DOCTYPE html>{% load static %}
<html lang="fa" dir="rtl">

<head>

    <meta charset="UTF-8">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% block head %} {% endblock head %}


    <link href="{% static 'style/icofont.css' %}" rel="stylesheet">

    <title>{% block title %} {% endblock %}</title>
</head>


<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pages:home' %}">فروشگاه</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">

                {% if request.user.is_authenticated %}
                <li>
                    <a href="{% url 'accounts:logout'  %}" class="nav-link active" aria-current="page">خروج</a>
                </li>
                <a href="{% url 'accounts:profile' %}" class="nav-link active" aria-current="page">پروفایل</a>
                {% else %}
                <a href="{% url 'accounts:register' %}" class="nav-link active" aria-current="page">ثبت نام</a>
                <a href="{% url 'accounts:login'  %}" class="nav-link active" aria-current="page">ورود</a>
                {% endif %}
                <a href="{% url 'orders:summary_cart' %}" class="nav-link active" aria-current="page">سبد خرید</a>


                <form novalidate action="{% url 'pages:home' %}">
                    {% csrf_token %}
                    {{ form_search }}
                    <input type="submit" class="btn btn-outline-info" value="بگرد">
                </form>


            </ul>
            {% block category %}

            {% endblock category %}
        </div>
    </div>
</nav>

<body>

{% include 'includes/messages.html' %}

<div class="body-content">
    {% block content %} {% endblock %}
</div>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</body>
</html>